/**
 * Frozen game-content localization. Entity IDs remain the product authority;
 * Chinese source labels are retained only as lookup fallbacks for API payloads.
 */
const petNames = [
  ["PET-N-001-1", "苔核芽", "Mossprout"],
  ["PET-N-001-2", "苔冠晶芽", "Crystabloom"],
  ["PET-N-001-3", "森晶巨冠", "Verdacrown"],
  ["PET-N-002-1", "炽尾核", "Cinderkin"],
  ["PET-N-002-2", "焰爪战体", "Blazetalon"],
  ["PET-N-002-3", "天焰翼皇", "Skyflare"],
  ["PET-N-003-1", "晶耳幼刺", "Glintspike"],
  ["PET-N-003-2", "棱脊刺姬", "Prismabriar"],
  ["PET-N-003-3", "甲裙毒后", "Vesperqueen"],
  ["PET-N-004-1", "圈鳍冰团", "Frostfin"],
  ["PET-N-004-2", "冠须冰轮", "Rimewhorl"],
  ["PET-N-004-3", "冰牙巨轮", "Glacignath"],
  ["PET-N-005-1", "金刺幼核", "Giltthorn"],
  ["PET-N-005-2", "金甲静体", "Auraguard"],
  ["PET-N-005-3", "赤针战翼", "Crimsonlance"],
  ["PET-N-006-1", "紫耳刺童", "Toxipip"],
  ["PET-N-006-2", "棘冠毒迅", "Briarush"],
  ["PET-N-006-3", "晶角毒王", "Amethyrant"],
  ["PET-N-007-1", "环触黏团", "Glooplet"],
  ["PET-N-007-2", "棱壳黏灵", "Slimeshard"],
  ["PET-N-007-3", "翼耳黏龙", "Oozephyr"],
  ["PET-N-008-1", "星耳电童", "Zapplet"],
  ["PET-N-008-2", "雷鬃迅灵", "Voltmane"],
  ["PET-N-008-3", "曜鬃电皇", "Stormcrown"],
  ["PET-N-009-1", "念星童", "Psiwisp"],
  ["PET-N-009-2", "双银翼兽", "Silverspan"],
  ["PET-N-009-3", "银甲战兽", "Argentitan"],
  ["PET-N-010-1", "力纹童", "Knucklet"],
  ["PET-N-010-2", "钢腕战体", "Bronzebrawl"],
  ["PET-N-010-3", "四臂武尊", "Tetratitan"],
  ["PET-N-011-1", "雾核灵", "Mistimp"],
  ["PET-N-011-2", "影爪笑灵", "Grinclaw"],
  ["PET-N-011-3", "紫影魔王", "Gloamfiend"],
  ["PET-N-012-1", "蓝珠幼灵", "Dewgem"],
  ["PET-N-012-2", "云环灵体", "Nimbusoul"],
  ["PET-N-012-3", "苍翼守皇", "Azurewarden"],
  ["PET-N-013-1", "月叶芽灵", "Moonbud"],
  ["PET-N-013-2", "叶颈灵", "Sylvaleaf"],
  ["PET-N-013-3", "花冠圣体", "Floradivine"],
  ["PET-N-014-1", "火脊芽", "Cinderidge"],
  ["PET-N-014-2", "焰背迅体", "Flareback"],
  ["PET-N-014-3", "烈焰暴君", "Infernotyr"],
  ["PET-N-015-1", "晶爪懒灵", "Drowseclaw"],
  ["PET-N-015-2", "双冠躁兽", "Crownrager"],
  ["PET-N-015-3", "纹胸巨座", "Runetitan"],
  ["PET-N-016-1", "星壳童", "Starshell"],
  ["PET-N-016-2", "云翼灵", "Cloudplume"],
  ["PET-N-016-3", "天星圣翼", "Celestwing"],
  ["PET-N-017-1", "黏晶芽", "Glimgoo"],
  ["PET-N-017-2", "壳涎灵体", "Shellslob"],
  ["PET-N-017-3", "雨角黏皇", "Monsooze"],
  ["PET-N-018-1", "砂甲幼核", "Pebblit"],
  ["PET-N-018-2", "岩壳静体", "Cragguard"],
  ["PET-N-018-3", "荒岩霸体", "Wastetitan"],
  ["PET-N-019-1", "月耳星芽", "Lunip"],
  ["PET-N-019-2", "旋耳月灵", "Moonwhirl"],
  ["PET-N-019-3", "云翼月姬", "Selunaria"],
  ["PET-N-020-1", "炎羽芽", "Emberplume"],
  ["PET-N-020-2", "焰腕斗体", "Flarebrace"],
  ["PET-N-020-3", "天火武皇", "Solphoenix"],
  ["PET-N-021-1", "潮鳍芽", "Puddlefin"],
  ["PET-N-021-2", "沼纹战体", "Marshmaul"],
  ["PET-N-021-3", "巨潮重体", "Tidalith"],
  ["PET-N-022-1", "念冠童", "Mindora"],
  ["PET-N-022-2", "心舞灵", "Heartwaltz"],
  ["PET-N-022-3", "星裙圣灵", "Astrabelle"],
  ["PET-N-023-1", "铁壳芽", "Ferrikid"],
  ["PET-N-023-2", "钢甲重体", "Steelmantle"],
  ["PET-N-023-3", "银铠巨尊", "Silvercolossus"],
  ["PET-N-024-1", "夜目灵", "Nightling"],
  ["PET-N-024-2", "绷带影体", "Shroudshade"],
  ["PET-N-024-3", "冥手巨灵", "Dreadhand"],
  ["PET-N-025-1", "银壳龙胚", "Silvershell"],
  ["PET-N-025-2", "颅甲芽", "Skullscale"],
  ["PET-N-025-3", "赤翼飞皇", "Crimsonwyvern"],
  ["PET-N-026-1", "苔甲芽", "Mossback"],
  ["PET-N-026-2", "林甲厚体", "Grovehide"],
  ["PET-N-026-3", "森岳载体", "Worldbark"],
  ["PET-N-027-1", "火尾灵", "Flickertail"],
  ["PET-N-027-2", "焰拳迅体", "Emberpunch"],
  ["PET-N-027-3", "烈焰斗圣", "Blazemaster"],
  ["PET-N-028-1", "蓝绒童", "Aquafuzz"],
  ["PET-N-028-2", "海冠礼体", "Tidemarque"],
  ["PET-N-028-3", "帝潮铠皇", "Oceanregent"],
  ["PET-N-029-1", "星耳芽", "Glimmerbit"],
  ["PET-N-029-2", "电鬃迅体", "Shockmane"],
  ["PET-N-029-3", "辉眼雷皇", "Thunderseer"],
  ["PET-N-030-1", "砂鳍芽", "Dunejaw"],
  ["PET-N-030-2", "刃鳍迅体", "Razorfin"],
  ["PET-N-030-3", "苍刃暴皇", "Cobaltmaw"],
  ["PET-N-031-1", "火耳灵", "Cinderear"],
  ["PET-N-031-2", "焰杖术体", "Pyrostaff"],
  ["PET-N-031-3", "赤焰法皇", "Emberarchon"],
  ["PET-N-032-1", "栗甲芽", "Acornik"],
  ["PET-N-032-2", "球甲护体", "Rollbark"],
  ["PET-N-032-3", "森铠巨卫", "Grovebulwark"],
  ["PET-N-033-1", "贝刃芽", "Shellshiv"],
  ["PET-N-033-2", "双刃潮体", "Tideblades"],
  ["PET-N-033-3", "海铠剑皇", "Marisaber"],
  ["PET-N-034-1", "线叶织童", "Threadbud"],
  ["PET-N-034-2", "双芽叶袍", "Leafweaver"],
  ["PET-N-034-3", "双镰叶姬", "Sickleflora"],
  ["PET-N-035-1", "毒节芽", "Venoseed"],
  ["PET-N-035-2", "星罩静体", "Astracocoon"],
  ["PET-N-035-3", "智域巨眼", "Omnivision"],
  ["PET-N-036-1", "泡鼻水童", "Bubblenose"],
  ["PET-N-036-2", "晶裙水舞", "Aquavelle"],
  ["PET-N-036-3", "星珠歌姬", "Pearlsong"],
  ["PET-N-037-1", "银脊冰牙", "Frostfang"],
  ["PET-N-037-2", "晶鼻雪鬃", "Snowcrest"],
  ["PET-N-037-3", "冰冠巨牙", "Glaciodon"],
  ["PET-N-038-1", "环叶浮童", "Leafloop"],
  ["PET-N-038-2", "晶掌伞灵", "Shroomshine"],
  ["PET-N-038-3", "鼓帽舞王", "Revelcap"],
  ["PET-N-039-1", "蓝烛芽", "Wicklet"],
  ["PET-N-039-2", "幽灯浮体", "Wispglow"],
  ["PET-N-039-3", "晶焰灯皇", "Prismalume"],
  ["PET-N-040-1", "斧牙芽", "Axebit"],
  ["PET-N-040-2", "刃颚战体", "Cleaverjaw"],
  ["PET-N-040-3", "双斧龙皇", "Twinaxion"],
  ["PET-A-001-1", "刃盔芽", "Edgesprig"],
  ["PET-A-001-2", "赤刃将体", "Crimsonmarshal"],
  ["PET-A-001-3", "黑刃统皇", "Obsidianblade"],
  ["PET-A-002-1", "炭芽蜥", "Charnewt"],
  ["PET-A-002-2", "焰脊蜥", "Pyrospine"],
  ["PET-A-002-3", "熔冠炎蜥", "Magmacrest"],
  ["PET-A-003-1", "青叶灵", "Leafkin"],
  ["PET-A-003-2", "藤纹灵体", "Vinesigil"],
  ["PET-A-003-3", "翠冠君体", "Verdantlord"],
  ["PET-A-004-1", "泡颈芽", "Foamruff"],
  ["PET-A-004-2", "蓝巾迅体", "Cobaltdash"],
  ["PET-A-004-3", "雷刃犀皇", "Stormrhino"],
  ["PET-A-005-1", "砾鼻甲兽", "Pebbletusk"],
  ["PET-A-005-2", "岩垒掘兽", "Cragburrow"],
  ["PET-A-005-3", "山垒镇甲兽", "Mountitan"],
  ["PET-A-006-1", "晶耳石核", "Geodear"],
  ["PET-A-006-2", "金缝四晶", "Goldvein"],
  ["PET-A-006-3", "双塔晶岩", "Spirequartz"],
  ["PET-A-007-1", "叉耳恶童", "Impincer"],
  ["PET-A-007-2", "翼发恶灵", "Hexplume"],
  ["PET-A-007-3", "荆鬃恶王", "Thornfiend"],
  ["PET-A-008-1", "油叶芽", "Saplet"],
  ["PET-A-008-2", "枝冠灵体", "Resinbranch"],
  ["PET-A-008-3", "绿油圣树", "Myrrhwood"],
  ["PET-A-009-1", "火纹芽", "Brandbud"],
  ["PET-A-009-2", "赤铃战体", "Bellbrawler"],
  ["PET-A-009-3", "烈焰摔皇", "Ringinferno"],
  ["PET-A-010-1", "泡冠童", "Bubbelle"],
  ["PET-A-010-2", "水裙歌体", "Tidearia"],
  ["PET-A-010-3", "海声歌姬", "Sirenova"],
  ["PET-A-011-1", "玉须曜龟", "Jadewhisk"],
  ["PET-A-011-2", "金背玉龟", "Auratortoise"],
  ["PET-A-011-3", "战神龙龟", "Wyrmfort"],
  ["PET-A-012-1", "幼晶兽", "Gemcub"],
  ["PET-A-012-2", "晶龙兽", "Prismadrake"],
  ["PET-A-012-3", "金晶龙皇", "Crownquartz"],
  ["PET-A-013-1", "心鳞芽", "Heartscale"],
  ["PET-A-013-2", "甲鳞战体", "Valiantscale"],
  ["PET-A-013-3", "杖尾龙尊", "Scepterwyrm"],
  ["PET-A-014-1", "鼓芽灵", "Beatbud"],
  ["PET-A-014-2", "双槌迅体", "Malletdash"],
  ["PET-A-014-3", "森鼓巨王", "Timberthrum"],
  ["PET-A-015-1", "火足芽", "Cindercore"],
  ["PET-A-015-2", "焰球王牌", "Flarecore"],
  ["PET-A-015-3", "霜棱心核", "Rimecore"],
  ["PET-A-016-1", "星苞源灵", "Starseed"],
  ["PET-A-016-2", "银河花使", "Galaxibloom"],
  ["PET-A-016-3", "万华宇庭", "Universalia"],
  ["PET-A-017-1", "冰背芽", "Rimeback"],
  ["PET-A-017-2", "冻脊战体", "Frostspine"],
  ["PET-A-017-3", "冰戟龙皇", "Glacialance"],
  ["PET-A-018-1", "炭盾幼角龙", "Coalhorn"],
  ["PET-A-018-2", "熔盾角龙", "Magmahorn"],
  ["PET-A-018-3", "火山王冠角龙", "Volcanocrown"],
  ["PET-A-019-1", "晶牙幼龙", "Gemfang"],
  ["PET-A-019-2", "节刃颚龙", "Razordrake"],
  ["PET-A-019-3", "雷翼巨龙", "Stormwing"],
  ["PET-A-020-1", "火鼻芽", "Snufflame"],
  ["PET-A-020-2", "炎环战体", "Blazering"],
  ["PET-A-020-3", "烈火武王", "Infernochamp"],
  ["PET-T-001-1", "潮晶幻体", "Tideglint"],
  ["PET-T-001-2", "深蓝宫使", "Azureoracle"],
  ["PET-T-001-3", "万潮海庭", "Thalassarch"],
  ["PET-T-002-1", "圣律铃核", "Chimekin"],
  ["PET-T-002-2", "天籁钟使", "Seraphone"],
  ["PET-T-002-3", "万音神庭", "Harmonarch"],
  ["PET-T-003-1", "火面芽", "Maskindle"],
  ["PET-T-003-2", "焰冠歌体", "Pyrochant"],
  ["PET-T-003-3", "骨焰声王", "Dirgeblaze"],
  ["PET-T-004-1", "沙辉碑灵", "Dunerune"],
  ["PET-T-004-2", "流金幻碑", "Giltmirage"],
  ["PET-T-004-3", "无尽沙庭", "Eternisand"],
  ["PET-T-005-1", "晨辉圣胚", "Dawnseed"],
  ["PET-T-005-2", "曙轮裁使", "Sunarbiter"],
  ["PET-T-005-3", "永昼圣庭", "Evernoon"],
  ["PET-T-006-1", "星棱核灵", "Starshard"],
  ["PET-T-006-2", "曜环星使", "Astralhalo"],
  ["PET-T-006-3", "诸界星冠", "Omnistar"],
  ["PET-T-007-1", "双相棱龙", "Prismdrake"],
  ["PET-T-007-2", "六界棱翼龙", "Hexawing"],
  ["PET-T-007-3", "混沌全谱棱龙皇", "Spectrarch"],
  ["PET-T-008-1", "灵根芽核", "Rootling"],
  ["PET-T-008-2", "万生树庭", "Worldbough"],
  ["PET-T-008-3", "森域神柱", "Sylvanpillar"],
  ["PET-T-009-1", "灵页书核", "Pagewisp"],
  ["PET-T-009-2", "万卷魂使", "Tomewarden"],
  ["PET-T-009-3", "终典神库", "Omnibrary"],
  ["PET-T-010-1", "暗首芽", "Gloamling"],
  ["PET-T-010-2", "双首暗体", "Dreadtwins"],
  ["PET-T-010-3", "冥皇", "Netherlord"],
] as const;
const chainThemes = [
  ["CHAIN-N-001", "森晶巨冠谱系", "Verdacrown Lineage"],
  ["CHAIN-N-002", "天焰翼皇谱系", "Skyflare Lineage"],
  ["CHAIN-N-003", "甲裙毒后谱系", "Vesperqueen Lineage"],
  ["CHAIN-N-004", "冰牙巨轮谱系", "Glacignath Lineage"],
  ["CHAIN-N-005", "赤针战翼谱系", "Crimsonlance Lineage"],
  ["CHAIN-N-006", "晶角毒王谱系", "Amethyrant Lineage"],
  ["CHAIN-N-007", "翼耳黏龙谱系", "Oozephyr Lineage"],
  ["CHAIN-N-008", "曜鬃电皇谱系", "Stormcrown Lineage"],
  ["CHAIN-N-009", "银甲战兽谱系", "Argentitan Lineage"],
  ["CHAIN-N-010", "四臂武尊谱系", "Tetratitan Lineage"],
  ["CHAIN-N-011", "紫影魔王谱系", "Gloamfiend Lineage"],
  ["CHAIN-N-012", "苍翼守皇谱系", "Azurewarden Lineage"],
  ["CHAIN-N-013", "花冠圣体谱系", "Floradivine Lineage"],
  ["CHAIN-N-014", "烈焰暴君谱系", "Infernotyr Lineage"],
  ["CHAIN-N-015", "纹胸巨座谱系", "Runetitan Lineage"],
  ["CHAIN-N-016", "天星圣翼谱系", "Celestwing Lineage"],
  ["CHAIN-N-017", "雨角黏皇谱系", "Monsooze Lineage"],
  ["CHAIN-N-018", "荒岩霸体谱系", "Wastetitan Lineage"],
  ["CHAIN-N-019", "云翼月姬谱系", "Selunaria Lineage"],
  ["CHAIN-N-020", "天火武皇谱系", "Solphoenix Lineage"],
  ["CHAIN-N-021", "巨潮重体谱系", "Tidalith Lineage"],
  ["CHAIN-N-022", "星裙圣灵谱系", "Astrabelle Lineage"],
  ["CHAIN-N-023", "银铠巨尊谱系", "Silvercolossus Lineage"],
  ["CHAIN-N-024", "冥手巨灵谱系", "Dreadhand Lineage"],
  ["CHAIN-N-025", "赤翼飞皇谱系", "Crimsonwyvern Lineage"],
  ["CHAIN-N-026", "森岳载体谱系", "Worldbark Lineage"],
  ["CHAIN-N-027", "烈焰斗圣谱系", "Blazemaster Lineage"],
  ["CHAIN-N-028", "帝潮铠皇谱系", "Oceanregent Lineage"],
  ["CHAIN-N-029", "辉眼雷皇谱系", "Thunderseer Lineage"],
  ["CHAIN-N-030", "苍刃暴皇谱系", "Cobaltmaw Lineage"],
  ["CHAIN-N-031", "赤焰法皇谱系", "Emberarchon Lineage"],
  ["CHAIN-N-032", "森铠巨卫谱系", "Grovebulwark Lineage"],
  ["CHAIN-N-033", "海铠剑皇谱系", "Marisaber Lineage"],
  ["CHAIN-N-034", "双镰叶姬谱系", "Sickleflora Lineage"],
  ["CHAIN-N-035", "智域巨眼谱系", "Omnivision Lineage"],
  ["CHAIN-N-036", "星珠歌姬谱系", "Pearlsong Lineage"],
  ["CHAIN-N-037", "冰冠巨牙谱系", "Glaciodon Lineage"],
  ["CHAIN-N-038", "鼓帽舞王谱系", "Revelcap Lineage"],
  ["CHAIN-N-039", "晶焰灯皇谱系", "Prismalume Lineage"],
  ["CHAIN-N-040", "双斧龙皇谱系", "Twinaxion Lineage"],
  ["CHAIN-A-001", "黑刃统皇谱系", "Obsidianblade Lineage"],
  ["CHAIN-A-002", "熔冠炎蜥谱系", "Magmacrest Lineage"],
  ["CHAIN-A-003", "翠冠君体谱系", "Verdantlord Lineage"],
  ["CHAIN-A-004", "雷刃犀皇谱系", "Stormrhino Lineage"],
  ["CHAIN-A-005", "山垒镇甲兽谱系", "Mountitan Lineage"],
  ["CHAIN-A-006", "双塔晶岩谱系", "Spirequartz Lineage"],
  ["CHAIN-A-007", "荆鬃恶王谱系", "Thornfiend Lineage"],
  ["CHAIN-A-008", "绿油圣树谱系", "Myrrhwood Lineage"],
  ["CHAIN-A-009", "烈焰摔皇谱系", "Ringinferno Lineage"],
  ["CHAIN-A-010", "海声歌姬谱系", "Sirenova Lineage"],
  ["CHAIN-A-011", "战神龙龟谱系", "Wyrmfort Lineage"],
  ["CHAIN-A-012", "金晶龙皇谱系", "Crownquartz Lineage"],
  ["CHAIN-A-013", "杖尾龙尊谱系", "Scepterwyrm Lineage"],
  ["CHAIN-A-014", "森鼓巨王谱系", "Timberthrum Lineage"],
  ["CHAIN-A-015", "霜棱心核谱系", "Rimecore Lineage"],
  ["CHAIN-A-016", "万华宇庭谱系", "Universalia Lineage"],
  ["CHAIN-A-017", "冰戟龙皇谱系", "Glacialance Lineage"],
  ["CHAIN-A-018", "火山王冠角龙谱系", "Volcanocrown Lineage"],
  ["CHAIN-A-019", "雷翼巨龙谱系", "Stormwing Lineage"],
  ["CHAIN-A-020", "烈火武王谱系", "Infernochamp Lineage"],
  ["CHAIN-T-001", "万潮海庭谱系", "Thalassarch Lineage"],
  ["CHAIN-T-002", "万音神庭谱系", "Harmonarch Lineage"],
  ["CHAIN-T-003", "骨焰声王谱系", "Dirgeblaze Lineage"],
  ["CHAIN-T-004", "无尽沙庭谱系", "Eternisand Lineage"],
  ["CHAIN-T-005", "永昼圣庭谱系", "Evernoon Lineage"],
  ["CHAIN-T-006", "诸界星冠谱系", "Omnistar Lineage"],
  ["CHAIN-T-007", "混沌全谱棱龙皇谱系", "Spectrarch Lineage"],
  ["CHAIN-T-008", "森域神柱谱系", "Sylvanpillar Lineage"],
  ["CHAIN-T-009", "终典神库谱系", "Omnibrary Lineage"],
  ["CHAIN-T-010", "冥皇谱系", "Netherlord Lineage"],
] as const;
const battleSkills = [
  ["fire-s01", "火花突袭", "Spark Rush"],
  ["grass-s01", "飞叶突袭", "Razorleaf Rush"],
  ["earth-s01", "砂砾突袭", "Gravel Rush"],
  ["lightning-s01", "电光突袭", "Volt Rush"],
  ["water-s01", "水流突袭", "Stream Rush"],
  ["fire-s02", "炽焰快攻", "Blaze Blitz"],
  ["grass-s02", "藤刺快攻", "Briar Blitz"],
  ["earth-s02", "岩针快攻", "Stone Spike"],
  ["lightning-s02", "雷针快攻", "Thunder Spike"],
  ["water-s02", "水刃快攻", "Aqua Blade"],
  ["fire-s03", "爆炎闪击", "Blastflare"],
  ["grass-s03", "荆棘闪击", "Thornflash"],
  ["earth-s03", "地裂闪击", "Riftstrike"],
  ["lightning-s03", "霆光闪击", "Thunderflash"],
  ["water-s03", "潮汐闪击", "Tideflash"],
  ["fire-s04", "灼热火球", "Scorch Orb"],
  ["grass-s04", "种子弹", "Seedshot"],
  ["earth-s04", "泥岩弹", "Mudstone Shot"],
  ["lightning-s04", "电弧弹", "Arc Bolt"],
  ["water-s04", "泡沫弹", "Bubble Burst"],
  ["fire-s05", "烈焰冲击", "Flame Impact"],
  ["grass-s05", "叶刃冲击", "Leafblade Impact"],
  ["earth-s05", "岩崩冲击", "Rockslide Impact"],
  ["lightning-s05", "雷鸣冲击", "Thunderclap"],
  ["water-s05", "激流冲击", "Riptide Impact"],
  ["fire-s06", "熔岩重击", "Magma Breaker"],
  ["grass-s06", "巨藤重击", "Titan Vine"],
  ["earth-s06", "山岳重击", "Mountain Breaker"],
  ["lightning-s06", "霹雳重击", "Bolt Breaker"],
  ["water-s06", "巨浪重击", "Tidal Breaker"],
  ["fire-s07", "日炎爆破", "Solar Detonation"],
  ["grass-s07", "森罗爆破", "Wildwood Detonation"],
  ["earth-s07", "地脉爆破", "Leyline Detonation"],
  ["lightning-s07", "雷暴爆破", "Storm Detonation"],
  ["water-s07", "海啸爆破", "Tsunami Detonation"],
  ["fire-s08", "焰流轰击", "Flame Torrent"],
  ["grass-s08", "古木轰击", "Ancient Timber"],
  ["earth-s08", "巨岩轰击", "Monolith Barrage"],
  ["lightning-s08", "磁极轰击", "Magnetic Barrage"],
  ["water-s08", "深潮轰击", "Deepcurrent Barrage"],
  ["fire-s09", "炼狱坠火", "Inferno Drop"],
  ["grass-s09", "万叶风暴", "Myriad Leafstorm"],
  ["earth-s09", "大地震荡", "Worldshaker"],
  ["lightning-s09", "九霄天雷", "Nine-Sky Thunder"],
  ["water-s09", "沧海怒涛", "Ocean's Fury"],
  ["fire-s10", "终焉天火", "Final Heavenfire"],
  ["grass-s10", "世界树坠击", "Worldtree Judgment"],
  ["earth-s10", "天陨坠岩", "Meteorstone Fall"],
  ["lightning-s10", "万雷天劫", "Heavenfall Thunder"],
  ["water-s10", "天河坠潮", "Celestial Deluge"],
] as const;

const tasks = [
  ["gacha_1.title", "今日单抽 1 次", "Make 1 Single Pull Today"],
  [
    "gacha_1.description",
    "当日完成 1 次付费单抽或使用免费资格单抽；十连不计入",
    "Complete one paid or free single pull today. 10-pulls do not count.",
  ],
  ["gacha_10.title", "今日单抽 10 次", "Make 10 Single Pulls Today"],
  [
    "gacha_10.description",
    "当日累计完成 10 次付费单抽或使用免费资格单抽；十连不计入",
    "Complete ten paid or free single pulls today. 10-pulls do not count.",
  ],
  ["gacha_ten.title", "完成 1 次十连", "Complete a 10-Pull"],
  [
    "gacha_ten.description",
    "当日一次十连整批成功；不计入单抽任务",
    "Complete one full 10-pull today. It does not count toward single-pull tasks.",
  ],
  ["wheel_spin.title", "每日转动转盘 1 次", "Spin the Prize Wheel"],
  [
    "wheel_spin.description",
    "当日单次转盘或十次转盘整批成功",
    "Complete either a single spin or a full 10-spin today.",
  ],
  ["market_buy.title", "市场购买 1 次", "Buy from the Marketplace"],
  [
    "market_buy.description",
    "当日市场购买整笔成功",
    "Complete one Marketplace purchase today.",
  ],
  ["market_list.title", "创建出售 1 次", "Create a Listing"],
  [
    "market_list.description",
    "当日创建出售整笔成功",
    "Create one successful Marketplace listing today.",
  ],
  ["market_sold.title", "成功卖出 1 次", "Sell a Collectible"],
  [
    "market_sold.description",
    "当日出售藏品产生真实成交",
    "Complete one collectible sale today.",
  ],
  ["evolution_success.title", "进化成功 1 次", "Complete an Evolution"],
  [
    "evolution_success.description",
    "当日进化结算为成功",
    "Successfully evolve one collectible today.",
  ],
  ["evolution_attempt.title", "尝试进化 1 次", "Attempt an Evolution"],
  [
    "evolution_attempt.description",
    "当日进化完成成功或失败结算；前置拒绝不计",
    "Finish one evolution attempt today, whether it succeeds or fails. Rejected attempts do not count.",
  ],
  ["decompose.title", "分解成功 1 次", "Decompose a Collectible"],
  [
    "decompose.description",
    "当日分解整笔成功",
    "Complete one decomposition today.",
  ],
  [
    "expedition_normal.title",
    "完成 1 次普通远征",
    "Complete a Standard Expedition",
  ],
  [
    "expedition_normal.description",
    "当日普通远征奖励领取成功",
    "Claim one Standard Expedition reward today.",
  ],
  [
    "expedition_intermediate.title",
    "完成 1 次中级远征",
    "Complete a Skilled Expedition",
  ],
  [
    "expedition_intermediate.description",
    "当日中级远征奖励领取成功",
    "Claim one Skilled Expedition reward today.",
  ],
  [
    "expedition_advanced.title",
    "完成 1 次高级远征",
    "Complete an Elite Expedition",
  ],
  [
    "expedition_advanced.description",
    "当日高级远征奖励领取成功",
    "Claim one Elite Expedition reward today.",
  ],
  ["album_unlock.title", "解锁 1 个新图鉴", "Discover a New Codex Entry"],
  [
    "album_unlock.description",
    "当日首次永久解锁 1 个此前未解锁的藏品模板",
    "Permanently discover one new collectible in the Codex today.",
  ],
  ["album_chain.title", "完成 1 条图鉴链", "Complete a Codex Lineage"],
  [
    "album_chain.description",
    "当日首次永久完成 1 条三节点图鉴链",
    "Complete a three-stage Codex lineage for the first time today.",
  ],
  ["wallet_verified.title", "钱包验证成功", "Verify Your Wallet"],
  [
    "wallet_verified.description",
    "当日新完成一次钱包验证",
    "Complete a new wallet verification today.",
  ],
  ["mint_success.title", "上链成功", "Mint On-Chain"],
  [
    "mint_success.description",
    "当日 Mint 链上成功结果获得确认",
    "Complete and confirm one on-chain mint today.",
  ],
] as const;

const otherContent = [
  ["box.normal", "普通盲盒", "Standard Mystery Box"],
  ["box.rare", "稀有盲盒", "Rare Mystery Box"],
  ["box.legendary", "传说盲盒", "Legendary Mystery Box"],
] as const;

type ContentEntry = readonly [
  id: string,
  simplifiedChinese: string,
  english: string,
];

const allContent: readonly ContentEntry[] = [
  ...petNames,
  ...chainThemes,
  ...battleSkills,
  ...tasks,
  ...otherContent,
];

const englishBySource = new Map<string, string>();
for (const [, simplifiedChinese, english] of allContent) {
  // Pet display names are listed first and remain canonical when a chain theme
  // intentionally reuses the same Chinese wording.
  if (!englishBySource.has(simplifiedChinese)) {
    englishBySource.set(simplifiedChinese, english);
  }
}
const englishById = new Map(allContent.map(([id, , english]) => [id, english]));
const simplifiedChineseById = new Map(
  allContent.map(([id, simplifiedChinese]) => [id, simplifiedChinese]),
);

export function englishGameContent(source: string): string | undefined {
  return englishBySource.get(source);
}

export function englishGameContentById(id: string): string | undefined {
  return englishById.get(id);
}

export function simplifiedChineseGameContentById(
  id: string,
): string | undefined {
  return simplifiedChineseById.get(id);
}

export const gameContentLocalizationCounts = Object.freeze({
  pets: petNames.length,
  chains: chainThemes.length,
  battleSkills: battleSkills.length,
  taskFields: tasks.length,
  other: otherContent.length,
});
