/**
 * Frozen game-content localization. Entity IDs remain the product authority;
 * Chinese source labels are retained only as lookup fallbacks for API payloads.
 */
const petNames = [
  ["PET-N-001-1", "炭尾狐", "Cindertail Kit"],
  ["PET-N-001-2", "焰鬃狐", "Blazemane Fox"],
  ["PET-N-001-3", "赤曜火狐", "Solarflare Vulpine"],
  ["PET-N-002-1", "溪泡獭", "Brookbubble Otter"],
  ["PET-N-002-2", "潮纹獭", "Tidemark Otter"],
  ["PET-N-002-3", "沧浪王獭", "Azurewave Otter King"],
  ["PET-N-003-1", "苔耳兔", "Mossear Bunny"],
  ["PET-N-003-2", "森跃兔", "Groveleap Hare"],
  ["PET-N-003-3", "翠冠灵兔", "Emerald Crown Jackalope"],
  ["PET-N-004-1", "砾甲龟", "Pebbleshell Tortoise"],
  ["PET-N-004-2", "岩垒龟", "Cragwall Tortoise"],
  ["PET-N-004-3", "玄岳巨龟", "Obsidian Mountain Tortoise"],
  ["PET-N-005-1", "风绒雀", "Breezefluff Finch"],
  ["PET-N-005-2", "岚翼雀", "Galecrest Finch"],
  ["PET-N-005-3", "青穹翔雀", "Azure Skywing"],
  ["PET-N-006-1", "灯粉蛾", "Glowdust Moth"],
  ["PET-N-006-2", "月灯蛾", "Moonlamp Moth"],
  ["PET-N-006-3", "辉幕幻蛾", "Radiant Veil Moth"],
  ["PET-N-007-1", "电须鼠", "Sparkwhisker"],
  ["PET-N-007-2", "霆尾鼠", "Thundertail"],
  ["PET-N-007-3", "雷极迅鼠", "Voltflash Rodent"],
  ["PET-N-008-1", "沙鳞蜥", "Sandscale Lizard"],
  ["PET-N-008-2", "漠脊蜥", "Duneback Lizard"],
  ["PET-N-008-3", "金尘龙蜥", "Golddust Drakescale"],
  ["PET-N-009-1", "雪团企鹅", "Snowball Penguin"],
  ["PET-N-009-2", "冰冠企鹅", "Icecrest Penguin"],
  ["PET-N-009-3", "极光帝企鹅", "Aurora Emperor Penguin"],
  ["PET-N-010-1", "竹团熊", "Bambooball Bear"],
  ["PET-N-010-2", "翠拳熊", "Jadefist Bear"],
  ["PET-N-010-3", "青竹武熊", "Bamboo Grandmaster"],
  ["PET-N-011-1", "珊钳蟹", "Coralclaw Crab"],
  ["PET-N-011-2", "礁甲蟹", "Reefplate Crab"],
  ["PET-N-011-3", "赤潮巨蟹", "Redtide Colossus Crab"],
  ["PET-N-012-1", "芽角鹿", "Budhorn Fawn"],
  ["PET-N-012-2", "花冠鹿", "Bloomcrown Stag"],
  ["PET-N-012-3", "森庭圣鹿", "Sanctuary Grove Stag"],
  ["PET-N-013-1", "云绒羊", "Cloudfleece Lamb"],
  ["PET-N-013-2", "霭角羊", "Misthorn Ram"],
  ["PET-N-013-3", "天幕云羊", "Skyveil Cloud Ram"],
  ["PET-N-014-1", "墨点鱿", "Inkdab Squid"],
  ["PET-N-014-2", "墨旋鱿", "Inkspiral Squid"],
  ["PET-N-014-3", "深海墨皇", "Abyssal Ink Emperor"],
  ["PET-N-015-1", "铜壳甲", "Coppershell Beetle"],
  ["PET-N-015-2", "锻角甲", "Forgehorn Beetle"],
  ["PET-N-015-3", "熔金战甲", "Molten Gold Juggernaut"],
  ["PET-N-016-1", "露珠蛙", "Dewdrop Frog"],
  ["PET-N-016-2", "荷冠蛙", "Lotuscrown Frog"],
  ["PET-N-016-3", "青泉灵蛙", "Jadespring Spirit Frog"],
  ["PET-N-017-1", "烬纹浣熊", "Emberstripe Raccoon"],
  ["PET-N-017-2", "灰焰浣熊", "Ashflame Raccoon"],
  ["PET-N-017-3", "焚林火浣", "Wildfire Raccoon"],
  ["PET-N-018-1", "雪眸鸮", "Snoweye Owlet"],
  ["PET-N-018-2", "霜翼鸮", "Frostwing Owl"],
  ["PET-N-018-3", "极夜雪鸮", "Polar Night Snow Owl"],
  ["PET-N-019-1", "蜜绒蜂", "Honeyfuzz Bee"],
  ["PET-N-019-2", "金巢蜂", "Goldhive Bee"],
  ["PET-N-019-3", "琥珀蜂后", "Amber Queen Bee"],
  ["PET-N-020-1", "泥鼻豚", "Mudsnout Piglet"],
  ["PET-N-020-2", "陶甲豚", "Clayplate Boar"],
  ["PET-N-020-3", "地脉岩豚", "Leyrock Boar"],
  ["PET-N-021-1", "芦影猫", "Reedshadow Kitten"],
  ["PET-N-021-2", "沼纹猫", "Marshmark Cat"],
  ["PET-N-021-3", "碧泽灵猫", "Jademarsh Spirit Cat"],
  ["PET-N-022-1", "晨羽雏", "Dawnfeather Chick"],
  ["PET-N-022-2", "旭冠鸟", "Sunrise Crested Bird"],
  ["PET-N-022-3", "曦光金翎", "Daybreak Goldenwing"],
  ["PET-N-023-1", "月耳蝠", "Moonear Bat"],
  ["PET-N-023-2", "暮翼蝠", "Duskwing Bat"],
  ["PET-N-023-3", "蚀月夜蝠", "Eclipse Nightbat"],
  ["PET-N-024-1", "橡果松鼠", "Acorn Squirrel"],
  ["PET-N-024-2", "松针飞鼠", "Pineglide Squirrel"],
  ["PET-N-024-3", "森藏王鼠", "Grovehoard Squirrel King"],
  ["PET-N-025-1", "琉光水母", "Glimmer Jelly"],
  ["PET-N-025-2", "镜海水母", "Mirrorsea Jelly"],
  ["PET-N-025-3", "虹幕水母", "Rainbow Veil Jelly"],
  ["PET-N-026-1", "梅斑猞", "Plumspot Lynx"],
  ["PET-N-026-2", "霜梅猞", "Frostplum Lynx"],
  ["PET-N-026-3", "寒梅影猞", "Winter Plum Shadowlynx"],
  ["PET-N-027-1", "雾绒牦", "Mistfleece Yak"],
  ["PET-N-027-2", "云脊牦", "Cloudridge Yak"],
  ["PET-N-027-3", "雪岭天牦", "Skycrest Snow Yak"],
  ["PET-N-028-1", "火芽螈", "Emberbud Newt"],
  ["PET-N-028-2", "熔纹螈", "Moltenscale Newt"],
  ["PET-N-028-3", "火山帝螈", "Volcano Emperor Newt"],
  ["PET-N-029-1", "荷叶鸭", "Lilypad Duckling"],
  ["PET-N-029-2", "莲冠鸭", "Lotuscrown Duck"],
  ["PET-N-029-3", "碧池莲皇", "Jadepond Lotus Sovereign"],
  ["PET-N-030-1", "晶爪鼹", "Crystalclaw Mole"],
  ["PET-N-030-2", "矿脊鼹", "Orebrow Mole"],
  ["PET-N-030-3", "晶窟巨鼹", "Crystal Cavern Megamole"],
  ["PET-N-031-1", "茶耳狸", "Teaear Civet"],
  ["PET-N-031-2", "香雾狸", "Aromamist Civet"],
  ["PET-N-031-3", "茶境灵狸", "Tea Garden Spirit Civet"],
  ["PET-N-032-1", "哨音豚", "Whistletune Dolphin"],
  ["PET-N-032-2", "潮笛豚", "Tideflute Dolphin"],
  ["PET-N-032-3", "蓝海歌豚", "Bluewater Song Dolphin"],
  ["PET-N-033-1", "蕨尾壁虎", "Ferntail Gecko"],
  ["PET-N-033-2", "藤甲壁虎", "Vineplate Gecko"],
  ["PET-N-033-3", "古森龙壁", "Ancient Grove Dracogecko"],
  ["PET-N-034-1", "糖翼鼯", "Sugarwing Glider"],
  ["PET-N-034-2", "蜜风鼯", "Honeybreeze Glider"],
  ["PET-N-034-3", "云糖飞鼯", "Cloudcandy Glider"],
  ["PET-N-035-1", "松果刺猬", "Pinecone Hedgehog"],
  ["PET-N-035-2", "针叶刺猬", "Needleleaf Hedgehog"],
  ["PET-N-035-3", "苍松甲猬", "Ironpine Hedgehog"],
  ["PET-N-036-1", "雨羽鹭", "Rainfeather Heron"],
  ["PET-N-036-2", "霖翎鹭", "Stormplume Heron"],
  ["PET-N-036-3", "天雨玄鹭", "Heavenrain Heron"],
  ["PET-N-037-1", "可可猿", "Cocoa Monkey"],
  ["PET-N-037-2", "豆甲猿", "Cacaopod Ape"],
  ["PET-N-037-3", "醇香森猿", "Mocha Grove Ape"],
  ["PET-N-038-1", "星砂海星", "Star-Sand Starfish"],
  ["PET-N-038-2", "晶潮海星", "Crystal Tide Starfish"],
  ["PET-N-038-3", "五曜星冠", "Prismatic Star Crown"],
  ["PET-N-039-1", "贝壳蜗", "Shellbud Snail"],
  ["PET-N-039-2", "珠纹蜗", "Pearlmark Snail"],
  ["PET-N-039-3", "珊宫宝蜗", "Coral Palace Jewel Snail"],
  ["PET-N-040-1", "风筝鳐", "Kitefin Ray"],
  ["PET-N-040-2", "云帆鳐", "Cloudsail Ray"],
  ["PET-N-040-3", "天幕巨鳐", "Skyveil Mantaray"],
  ["PET-A-001-1", "霜璃狐", "Frostglass Fox"],
  ["PET-A-001-2", "寒镜灵狐", "Wintermirror Fox"],
  ["PET-A-001-3", "九霄冰狐", "Nine-Heaven Ice Fox"],
  ["PET-A-002-1", "雷角狮", "Thunderhorn Lion"],
  ["PET-A-002-2", "霆铠狮", "Stormplate Lion"],
  ["PET-A-002-3", "天罚雷狮", "Heavenscourge Lion"],
  ["PET-A-003-1", "碧潮蛟", "Jadetide Drake"],
  ["PET-A-003-2", "沧海蛟", "Azuresea Drake"],
  ["PET-A-003-3", "镇海苍蛟", "Oceanwarden Drake"],
  ["PET-A-004-1", "影羽鸦", "Shadowfeather Raven"],
  ["PET-A-004-2", "夜幕鸦", "Nightveil Raven"],
  ["PET-A-004-3", "冥月玄鸦", "Nethermoon Raven"],
  ["PET-A-005-1", "炎角鹿", "Flamehorn Fawn"],
  ["PET-A-005-2", "熔冠鹿", "Moltencrown Stag"],
  ["PET-A-005-3", "烈阳圣鹿", "Blazing Sun Stag"],
  ["PET-A-006-1", "晶翼蝶", "Crystalwing Butterfly"],
  ["PET-A-006-2", "镜华蝶", "Mirrorbloom Butterfly"],
  ["PET-A-006-3", "幻晶蝶后", "Phantom Crystal Empress"],
  ["PET-A-007-1", "岩心猿", "Stoneheart Ape"],
  ["PET-A-007-2", "山铠猿", "Mountainplate Ape"],
  ["PET-A-007-3", "擎岳神猿", "Titanpeak Ape"],
  ["PET-A-008-1", "星纹豹", "Starstripe Leopard"],
  ["PET-A-008-2", "曜影豹", "Astralshadow Leopard"],
  ["PET-A-008-3", "星陨猎豹", "Starfall Hunter"],
  ["PET-A-009-1", "风铃鹤", "Windchime Crane"],
  ["PET-A-009-2", "岚音鹤", "Galecall Crane"],
  ["PET-A-009-3", "九天风鹤", "Nine-Sky Wind Crane"],
  ["PET-A-010-1", "毒棘蝎", "Venomthorn Scorpion"],
  ["PET-A-010-2", "幽棘蝎", "Ghostthorn Scorpion"],
  ["PET-A-010-3", "紫冥蝎王", "Violet Nether Scorpion King"],
  ["PET-A-011-1", "潮歌鲸", "Tidesong Whale"],
  ["PET-A-011-2", "蓝穹鲸", "Bluevault Whale"],
  ["PET-A-011-3", "深渊歌鲸", "Abyssal Songwhale"],
  ["PET-A-012-1", "金羽鹰", "Goldfeather Eagle"],
  ["PET-A-012-2", "曜金鹰", "Sunsteel Eagle"],
  ["PET-A-012-3", "苍穹帝鹰", "Skylord Imperial Eagle"],
  ["PET-A-013-1", "月桂狼", "Laurel Wolf"],
  ["PET-A-013-2", "银月狼", "Silvermoon Wolf"],
  ["PET-A-013-3", "啸月狼皇", "Moonhowl Alpha"],
  ["PET-A-014-1", "熔炉犀", "Forgecore Rhino"],
  ["PET-A-014-2", "赤钢犀", "Redsteel Rhino"],
  ["PET-A-014-3", "熔城巨犀", "Molten Citadel Rhino"],
  ["PET-A-015-1", "梦砂貘", "Dreamsand Tapir"],
  ["PET-A-015-2", "幻沙貘", "Miragesand Tapir"],
  ["PET-A-015-3", "永梦灵貘", "EverDream Spirit Tapir"],
  ["PET-A-016-1", "青焰蛇", "Azureflame Serpent"],
  ["PET-A-016-2", "碧炎蟒", "Jadefire Python"],
  ["PET-A-016-3", "苍炎蛇皇", "Cerulean Flame Serpent King"],
  ["PET-A-017-1", "花镜鹿", "Bloomglass Fawn"],
  ["PET-A-017-2", "万华鹿", "Kaleidoscope Stag"],
  ["PET-A-017-3", "百花圣鹿", "Hundred-Bloom Sacred Stag"],
  ["PET-A-018-1", "磁极熊", "Magnetpaw Bear"],
  ["PET-A-018-2", "极光熊", "Aurora Bear"],
  ["PET-A-018-3", "北辰巨熊", "Northstar Great Bear"],
  ["PET-A-019-1", "镜湖鹅", "Mirrorlake Swan"],
  ["PET-A-019-2", "星湖天鹅", "Starlake Swan"],
  ["PET-A-019-3", "星河天鹅", "Galaxy Swan"],
  ["PET-A-020-1", "齿轮猫", "Gearkit Cat"],
  ["PET-A-020-2", "机芯灵猫", "Clockwork Spirit Cat"],
  ["PET-A-020-3", "天工圣猫", "Celestial Clockwork Cat"],
  ["PET-T-001-1", "曙星幼龙", "Dawnstar Wyrmling"],
  ["PET-T-001-2", "天穹星龙", "Celestial Star Dragon"],
  ["PET-T-001-3", "创界星神龙", "Worldforge Astral Dragon"],
  ["PET-T-002-1", "虚潮幼鲸", "Voidtide Calf"],
  ["PET-T-002-2", "裂界天鲸", "Riftbreaker Skywhale"],
  ["PET-T-002-3", "无垠虚空鲸", "Infinite Voidwhale"],
  ["PET-T-003-1", "日冕雏凰", "Corona Phoenix Chick"],
  ["PET-T-003-2", "炽天炎凰", "Empyrean Fire Phoenix"],
  ["PET-T-003-3", "永昼太阳神凰", "Eternal Sun Phoenix"],
  ["PET-T-004-1", "太阴灵狐", "Moonshade Spirit Fox"],
  ["PET-T-004-2", "月蚀九尾", "Eclipse Nine-Tails"],
  ["PET-T-004-3", "太阴月神狐", "Lunar Goddess Fox"],
  ["PET-T-005-1", "纪元幼龟", "Epoch Hatchling"],
  ["PET-T-005-2", "岁轮玄龟", "Agewheel Tortoise"],
  ["PET-T-005-3", "万古时轮神龟", "Eternal Timewheel Tortoise"],
  ["PET-T-006-1", "混沌幼狮", "Chaos Lion Cub"],
  ["PET-T-006-2", "界王圣狮", "Realmking Sacred Lion"],
  ["PET-T-006-3", "混沌创世神狮", "Chaos Genesis Lion"],
  ["PET-T-007-1", "天河幼鹿", "Starstream Fawn"],
  ["PET-T-007-2", "银河圣鹿", "Milky Way Sacred Stag"],
  ["PET-T-007-3", "森罗宇宙神鹿", "Cosmic Worldtree Stag"],
  ["PET-T-008-1", "霆麟幼兽", "Stormscale Kirin Cub"],
  ["PET-T-008-2", "九霄雷麟", "Nine-Sky Thunder Kirin"],
  ["PET-T-008-3", "万雷天劫麒麟", "Heavenfall Thunder Kirin"],
  ["PET-T-009-1", "渊鳞幼蛇", "Abysscale Serpentling"],
  ["PET-T-009-2", "灭界巨蟒", "Worldbane Python"],
  ["PET-T-009-3", "无光深渊神蛇", "Lightless Abyss Serpent"],
  ["PET-T-010-1", "法纹幼蝶", "Runemark Butterfly"],
  ["PET-T-010-2", "因果天蝶", "Karmic Sky Butterfly"],
  ["PET-T-010-3", "命运法则神蝶", "Fateweaver Divine Butterfly"],
] as const;

const chainThemes = [
  ["CHAIN-N-001", "余烬火狐", "Emberfox Lineage"],
  ["CHAIN-N-002", "溪流水獭", "Brooktide Otters"],
  ["CHAIN-N-003", "苔原灵兔", "Mosswood Hares"],
  ["CHAIN-N-004", "山岩甲龟", "Mountain-Shell Tortoises"],
  ["CHAIN-N-005", "青空风雀", "Azure Skyfinches"],
  ["CHAIN-N-006", "月灯幻蛾", "Moonlamp Moths"],
  ["CHAIN-N-007", "雷尾电鼠", "Thundertail Rodents"],
  ["CHAIN-N-008", "金沙龙蜥", "Goldsand Drakescales"],
  ["CHAIN-N-009", "极光企鹅", "Aurora Penguins"],
  ["CHAIN-N-010", "翠竹武熊", "Bamboo Grandmasters"],
  ["CHAIN-N-011", "赤潮珊蟹", "Redtide Coral Crabs"],
  ["CHAIN-N-012", "森庭角鹿", "Sanctuary Grove Stags"],
  ["CHAIN-N-013", "天幕云羊", "Skyveil Cloud Rams"],
  ["CHAIN-N-014", "深海墨鱿", "Abyssal Ink Squids"],
  ["CHAIN-N-015", "熔金角甲", "Molten Gold Beetles"],
  ["CHAIN-N-016", "青泉荷蛙", "Jadespring Lotus Frogs"],
  ["CHAIN-N-017", "灰烬浣熊", "Ashflame Raccoons"],
  ["CHAIN-N-018", "极夜雪鸮", "Polar Night Snow Owls"],
  ["CHAIN-N-019", "琥珀蜂群", "Amber Hive"],
  ["CHAIN-N-020", "地脉岩豚", "Leyrock Boars"],
  ["CHAIN-N-021", "碧泽芦猫", "Jademarsh Reed Cats"],
  ["CHAIN-N-022", "曦光金翎", "Daybreak Goldenwings"],
  ["CHAIN-N-023", "蚀月夜蝠", "Eclipse Nightbats"],
  ["CHAIN-N-024", "森藏松鼠", "Grovehoard Squirrels"],
  ["CHAIN-N-025", "虹幕水母", "Rainbow Veil Jellies"],
  ["CHAIN-N-026", "寒梅影猞", "Winter Plum Shadowlynx"],
  ["CHAIN-N-027", "雪岭天牦", "Skycrest Snow Yaks"],
  ["CHAIN-N-028", "火山帝螈", "Volcano Emperor Newts"],
  ["CHAIN-N-029", "碧池莲鸭", "Jadepond Lotus Ducks"],
  ["CHAIN-N-030", "晶窟巨鼹", "Crystal Cavern Moles"],
  ["CHAIN-N-031", "茶境灵狸", "Tea Garden Spirit Civets"],
  ["CHAIN-N-032", "蓝海歌豚", "Bluewater Song Dolphins"],
  ["CHAIN-N-033", "古森龙壁", "Ancient Grove Dracogeckos"],
  ["CHAIN-N-034", "云糖飞鼯", "Cloudcandy Gliders"],
  ["CHAIN-N-035", "苍松甲猬", "Ironpine Hedgehogs"],
  ["CHAIN-N-036", "天雨玄鹭", "Heavenrain Herons"],
  ["CHAIN-N-037", "醇香森猿", "Mocha Grove Apes"],
  ["CHAIN-N-038", "五曜星冠", "Prismatic Star Crown"],
  ["CHAIN-N-039", "珊宫宝蜗", "Coral Palace Jewel Snails"],
  ["CHAIN-N-040", "天幕巨鳐", "Skyveil Mantarays"],
  ["CHAIN-A-001", "九霄冰狐", "Nine-Heaven Ice Foxes"],
  ["CHAIN-A-002", "天罚雷狮", "Heavenscourge Lions"],
  ["CHAIN-A-003", "镇海苍蛟", "Oceanwarden Drakes"],
  ["CHAIN-A-004", "冥月玄鸦", "Nethermoon Ravens"],
  ["CHAIN-A-005", "烈阳圣鹿", "Blazing Sun Stags"],
  ["CHAIN-A-006", "幻晶蝶后", "Phantom Crystal Empresses"],
  ["CHAIN-A-007", "擎岳神猿", "Titanpeak Apes"],
  ["CHAIN-A-008", "星陨猎豹", "Starfall Hunters"],
  ["CHAIN-A-009", "九天风鹤", "Nine-Sky Wind Cranes"],
  ["CHAIN-A-010", "紫冥蝎王", "Violet Nether Scorpions"],
  ["CHAIN-A-011", "深渊歌鲸", "Abyssal Songwhales"],
  ["CHAIN-A-012", "苍穹帝鹰", "Skylord Imperial Eagles"],
  ["CHAIN-A-013", "啸月狼皇", "Moonhowl Alphas"],
  ["CHAIN-A-014", "熔城巨犀", "Molten Citadel Rhinos"],
  ["CHAIN-A-015", "永梦灵貘", "EverDream Spirit Tapirs"],
  ["CHAIN-A-016", "苍炎蛇皇", "Cerulean Flame Serpents"],
  ["CHAIN-A-017", "百花圣鹿", "Hundred-Bloom Sacred Stags"],
  ["CHAIN-A-018", "北辰巨熊", "Northstar Great Bears"],
  ["CHAIN-A-019", "星河天鹅", "Galaxy Swans"],
  ["CHAIN-A-020", "天工圣猫", "Celestial Clockwork Cats"],
  ["CHAIN-T-001", "创界星神龙", "Worldforge Astral Dragon"],
  ["CHAIN-T-002", "无垠虚空鲸", "Infinite Voidwhale"],
  ["CHAIN-T-003", "永昼太阳神凰", "Eternal Sun Phoenix"],
  ["CHAIN-T-004", "太阴月神狐", "Lunar Goddess Fox"],
  ["CHAIN-T-005", "万古时轮神龟", "Eternal Timewheel Tortoise"],
  ["CHAIN-T-006", "混沌创世神狮", "Chaos Genesis Lion"],
  ["CHAIN-T-007", "森罗宇宙神鹿", "Cosmic Worldtree Stag"],
  ["CHAIN-T-008", "万雷天劫麒麟", "Heavenfall Thunder Kirin"],
  ["CHAIN-T-009", "无光深渊神蛇", "Lightless Abyss Serpent"],
  ["CHAIN-T-010", "命运法则神蝶", "Fateweaver Divine Butterfly"],
] as const;

const battleSkills = [
  ["fire-s01", "火花突袭", "Spark Rush"],
  ["grass-s01", "飞叶突袭", "Razorleaf Rush"],
  ["earth-s01", "砂砾突袭", "Gravel Rush"],
  ["lightning-s01", "电光突袭", "Volt Rush"],
  ["water-s01", "水流突袭", "Stream Rush"],
  ["fire-s02", "炽焰快攻", "Blaze Blitz"],
  ["grass-s02", "藤刺快攻", "Briar Blitz"],
  ["earth-s02", "岩针快攻", "Stone Spike"],
  ["lightning-s02", "雷针快攻", "Thunder Spike"],
  ["water-s02", "水刃快攻", "Aqua Blade"],
  ["fire-s03", "爆炎闪击", "Blastflare"],
  ["grass-s03", "荆棘闪击", "Thornflash"],
  ["earth-s03", "地裂闪击", "Riftstrike"],
  ["lightning-s03", "霆光闪击", "Thunderflash"],
  ["water-s03", "潮汐闪击", "Tideflash"],
  ["fire-s04", "灼热火球", "Scorch Orb"],
  ["grass-s04", "种子弹", "Seedshot"],
  ["earth-s04", "泥岩弹", "Mudstone Shot"],
  ["lightning-s04", "电弧弹", "Arc Bolt"],
  ["water-s04", "泡沫弹", "Bubble Burst"],
  ["fire-s05", "烈焰冲击", "Flame Impact"],
  ["grass-s05", "叶刃冲击", "Leafblade Impact"],
  ["earth-s05", "岩崩冲击", "Rockslide Impact"],
  ["lightning-s05", "雷鸣冲击", "Thunderclap"],
  ["water-s05", "激流冲击", "Riptide Impact"],
  ["fire-s06", "熔岩重击", "Magma Breaker"],
  ["grass-s06", "巨藤重击", "Titan Vine"],
  ["earth-s06", "山岳重击", "Mountain Breaker"],
  ["lightning-s06", "霹雳重击", "Bolt Breaker"],
  ["water-s06", "巨浪重击", "Tidal Breaker"],
  ["fire-s07", "日炎爆破", "Solar Detonation"],
  ["grass-s07", "森罗爆破", "Wildwood Detonation"],
  ["earth-s07", "地脉爆破", "Leyline Detonation"],
  ["lightning-s07", "雷暴爆破", "Storm Detonation"],
  ["water-s07", "海啸爆破", "Tsunami Detonation"],
  ["fire-s08", "焰流轰击", "Flame Torrent"],
  ["grass-s08", "古木轰击", "Ancient Timber"],
  ["earth-s08", "巨岩轰击", "Monolith Barrage"],
  ["lightning-s08", "磁极轰击", "Magnetic Barrage"],
  ["water-s08", "深潮轰击", "Deepcurrent Barrage"],
  ["fire-s09", "炼狱坠火", "Inferno Drop"],
  ["grass-s09", "万叶风暴", "Myriad Leafstorm"],
  ["earth-s09", "大地震荡", "Worldshaker"],
  ["lightning-s09", "九霄天雷", "Nine-Sky Thunder"],
  ["water-s09", "沧海怒涛", "Ocean's Fury"],
  ["fire-s10", "终焉天火", "Final Heavenfire"],
  ["grass-s10", "世界树坠击", "Worldtree Judgment"],
  ["earth-s10", "天陨坠岩", "Meteorstone Fall"],
  ["lightning-s10", "万雷天劫", "Heavenfall Thunder"],
  ["water-s10", "天河坠潮", "Celestial Deluge"],
] as const;

const tasks = [
  ["gacha_1.title", "今日单抽 1 次", "Make 1 Single Pull Today"],
  [
    "gacha_1.description",
    "当日完成 1 次付费单抽或使用免费资格单抽；十连不计入",
    "Complete one paid or free single pull today. 10-pulls do not count.",
  ],
  ["gacha_10.title", "今日单抽 10 次", "Make 10 Single Pulls Today"],
  [
    "gacha_10.description",
    "当日累计完成 10 次付费单抽或使用免费资格单抽；十连不计入",
    "Complete ten paid or free single pulls today. 10-pulls do not count.",
  ],
  ["gacha_ten.title", "完成 1 次十连", "Complete a 10-Pull"],
  [
    "gacha_ten.description",
    "当日一次十连整批成功；不计入单抽任务",
    "Complete one full 10-pull today. It does not count toward single-pull tasks.",
  ],
  ["wheel_spin.title", "每日转动转盘 1 次", "Spin the Prize Wheel"],
  [
    "wheel_spin.description",
    "当日单次转盘或十次转盘整批成功",
    "Complete either a single spin or a full 10-spin today.",
  ],
  ["market_buy.title", "市场购买 1 次", "Buy from the Marketplace"],
  [
    "market_buy.description",
    "当日市场购买整笔成功",
    "Complete one Marketplace purchase today.",
  ],
  ["market_list.title", "创建出售 1 次", "Create a Listing"],
  [
    "market_list.description",
    "当日创建出售整笔成功",
    "Create one successful Marketplace listing today.",
  ],
  ["market_sold.title", "成功卖出 1 次", "Sell a Collectible"],
  [
    "market_sold.description",
    "当日出售藏品产生真实成交",
    "Complete one collectible sale today.",
  ],
  ["evolution_success.title", "进化成功 1 次", "Complete an Evolution"],
  [
    "evolution_success.description",
    "当日进化结算为成功",
    "Successfully evolve one collectible today.",
  ],
  ["evolution_attempt.title", "尝试进化 1 次", "Attempt an Evolution"],
  [
    "evolution_attempt.description",
    "当日进化完成成功或失败结算；前置拒绝不计",
    "Finish one evolution attempt today, whether it succeeds or fails. Rejected attempts do not count.",
  ],
  ["decompose.title", "分解成功 1 次", "Decompose a Collectible"],
  [
    "decompose.description",
    "当日分解整笔成功",
    "Complete one decomposition today.",
  ],
  [
    "expedition_normal.title",
    "完成 1 次普通远征",
    "Complete a Standard Expedition",
  ],
  [
    "expedition_normal.description",
    "当日普通远征奖励领取成功",
    "Claim one Standard Expedition reward today.",
  ],
  [
    "expedition_intermediate.title",
    "完成 1 次中级远征",
    "Complete a Skilled Expedition",
  ],
  [
    "expedition_intermediate.description",
    "当日中级远征奖励领取成功",
    "Claim one Skilled Expedition reward today.",
  ],
  [
    "expedition_advanced.title",
    "完成 1 次高级远征",
    "Complete an Elite Expedition",
  ],
  [
    "expedition_advanced.description",
    "当日高级远征奖励领取成功",
    "Claim one Elite Expedition reward today.",
  ],
  ["album_unlock.title", "解锁 1 个新图鉴", "Discover a New Codex Entry"],
  [
    "album_unlock.description",
    "当日首次永久解锁 1 个此前未解锁的藏品模板",
    "Permanently discover one new collectible in the Codex today.",
  ],
  ["album_chain.title", "完成 1 条图鉴链", "Complete a Codex Lineage"],
  [
    "album_chain.description",
    "当日首次永久完成 1 条三节点图鉴链",
    "Complete a three-stage Codex lineage for the first time today.",
  ],
  ["wallet_verified.title", "钱包验证成功", "Verify Your Wallet"],
  [
    "wallet_verified.description",
    "当日新完成一次钱包验证",
    "Complete a new wallet verification today.",
  ],
  ["mint_success.title", "上链成功", "Mint On-Chain"],
  [
    "mint_success.description",
    "当日 Mint 链上成功结果获得确认",
    "Complete and confirm one on-chain mint today.",
  ],
] as const;

const otherContent = [
  ["box.normal", "普通盲盒", "Standard Mystery Box"],
  ["box.rare", "稀有盲盒", "Rare Mystery Box"],
  ["box.legendary", "传说盲盒", "Legendary Mystery Box"],
] as const;

type ContentEntry = readonly [
  id: string,
  simplifiedChinese: string,
  english: string,
];

const allContent: readonly ContentEntry[] = [
  ...petNames,
  ...chainThemes,
  ...battleSkills,
  ...tasks,
  ...otherContent,
];

const englishBySource = new Map<string, string>();
for (const [, simplifiedChinese, english] of allContent) {
  // Pet display names are listed first and remain canonical when a chain theme
  // intentionally reuses the same Chinese wording.
  if (!englishBySource.has(simplifiedChinese)) {
    englishBySource.set(simplifiedChinese, english);
  }
}
const englishById = new Map(allContent.map(([id, , english]) => [id, english]));
const simplifiedChineseById = new Map(
  allContent.map(([id, simplifiedChinese]) => [id, simplifiedChinese]),
);

export function englishGameContent(source: string): string | undefined {
  return englishBySource.get(source);
}

export function englishGameContentById(id: string): string | undefined {
  return englishById.get(id);
}

export function simplifiedChineseGameContentById(
  id: string,
): string | undefined {
  return simplifiedChineseById.get(id);
}

export const gameContentLocalizationCounts = Object.freeze({
  pets: petNames.length,
  chains: chainThemes.length,
  battleSkills: battleSkills.length,
  taskFields: tasks.length,
  other: otherContent.length,
});
