#!/usr/bin/env python3
"""Build frozen product data SQL and the catalog manifest from the product document."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

import battle
import catalog
import gacha
import payments
import tasks


ROOT = Path(__file__).resolve().parents[2]
PRODUCT = ROOT / "docs/product/功能说明文档.md"
MIGRATIONS = ROOT / "supabase/migrations"
MANIFEST = ROOT / "generated/catalog/catalog-v1.json"
BATTLE_ROOT = ROOT / "generated/battle"
BATTLE_MANIFEST = BATTLE_ROOT / "manifest.json"
BATTLE_JSON = BATTLE_ROOT / "battle-v1.json"
BATTLE_SHA256 = BATTLE_ROOT / "battle-v1.sha256"
BATTLE_SQL = BATTLE_ROOT / "battle-v1.sql"
WEB_EVOLUTION_MANIFEST = (
    ROOT / "apps/web/src/domains/evolution/evolution-catalog-v1.json"
)
ASSET_ROOT = ROOT / "apps/web/public/assets"
PRODUCT_DATA_CHECKSUM_BOUNDARY = "<!-- PRODUCT_DATA_CHECKSUM_BOUNDARY -->"
EVOLUTION_RULES = {
    "rare": {"success_rate_percent": 95, "fgems_cost": 30},
    "epic": {"success_rate_percent": 60, "fgems_cost": 120},
    "legendary": {"success_rate_percent": 35, "fgems_cost": 500},
    "mythic": {"success_rate_percent": 20, "fgems_cost": 2000},
}


def split_product_document(markdown: str) -> tuple[str, str]:
    parts = markdown.split(PRODUCT_DATA_CHECKSUM_BOUNDARY)
    if len(parts) != 2:
        raise RuntimeError("Product document must contain exactly one product-data checksum boundary")
    product_data_source, product_extensions = parts
    if not product_data_source.strip() or not product_extensions.strip():
        raise RuntimeError("Product-data checksum boundary must separate the frozen source from product extensions")
    return product_data_source, product_extensions


def product_data_migration() -> Path:
    matches = sorted(MIGRATIONS.glob("*_product_data_v1.sql"))
    if len(matches) != 1:
        raise RuntimeError(f"Expected one *_product_data_v1.sql migration, found {len(matches)}")
    return matches[0]


def released_product_checksum() -> str:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    checksum = manifest.get("product_checksum")
    if manifest.get("version") != "v1" or not isinstance(checksum, str) or re.fullmatch(r"[0-9a-f]{64}", checksum) is None:
        raise RuntimeError("Tracked catalog v1 manifest has an invalid immutable product checksum")
    migration = product_data_migration().read_text(encoding="utf-8")
    required = (
        f"-- Product checksum: {checksum}",
        f"insert into catalog.versions (id, product_checksum) values ('v1', '{checksum}');",
    )
    if any(value not in migration for value in required):
        raise RuntimeError("Tracked catalog v1 manifest and product-data migration checksums differ")
    return checksum


def build_sql(
    chains: list[dict[str, object]],
    templates: list[dict[str, object]],
    checksum: str,
    battle_payload: dict[str, object],
) -> str:
    sections = [
        f"-- Generated by python3 tools/product_data/build.py. Do not hand edit.\n-- Product checksum: {checksum}\n\n",
        f"insert into catalog.versions (id, product_checksum) values ('v1', '{checksum}');\n\n",
        catalog.render(chains, templates),
        "\n",
        gacha.render(),
        "\n",
        payments.render(),
        "\n",
        tasks.render(),
        "\n",
        battle.render(battle_payload),
        "\nselect cron.schedule(\n"
        "  'battle-tick-v1',\n"
        "  '1 second',\n"
        "  $battle_tick$select battle.process_due(100);$battle_tick$\n"
        ");\n",
    ]
    return "".join(sections)


def build_web_evolution_manifest(
    templates: list[dict[str, object]],
) -> dict[str, object]:
    by_chain_stage = {
        (template["chain_id"], template["stage"]): template
        for template in templates
    }
    routes = []
    for source in templates:
        target = by_chain_stage.get((source["chain_id"], int(source["stage"]) + 1))
        if target is None:
            continue
        rule = EVOLUTION_RULES[str(target["rarity"])]
        routes.append(
            {
                "source_template_id": source["id"],
                "target": {
                    "template_id": target["id"],
                    "name": target["name"],
                    "rarity": target["rarity"],
                    "stage": target["stage"],
                    "image_thumbnail_path": target["image_thumbnail_path"],
                },
                **rule,
            }
        )
    if len(routes) != 140:
        raise RuntimeError(f"Expected 140 evolution routes, got {len(routes)}")
    return {"version": "v1", "routes": routes}


def asset_files(templates: list[dict[str, object]]) -> list[Path]:
    required = [
        ROOT / "apps/web/public" / str(item[key]).lstrip("/")
        for item in templates
        for key in ("image_thumbnail_path", "image_detail_path")
    ]
    required += [
        ASSET_ROOT / "boxes/normal.webp",
        ASSET_ROOT / "boxes/rare.webp",
        ASSET_ROOT / "boxes/legendary.webp",
        ASSET_ROOT / "share/preview.webp",
        ASSET_ROOT / "ton/tonconnect-icon.png",
    ]
    return required


def pin_assets(templates: list[dict[str, object]]) -> dict[str, str]:
    required = asset_files(templates)
    missing = [str(path.relative_to(ROOT)) for path in required if not path.is_file() or path.stat().st_size == 0]
    if missing:
        raise SystemExit("Missing required assets:\n" + "\n".join(missing))
    pinned = {str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest() for path in required}
    return pinned


def check_assets(templates: list[dict[str, object]], expected: object) -> None:
    required = asset_files(templates)
    if not isinstance(expected, dict) or set(expected) != {str(path.relative_to(ROOT)) for path in required}:
        raise SystemExit("Asset checksums are not pinned. Run product data build with --pin-assets after uploading all official assets.")
    mismatched = []
    for path in required:
        name = str(path.relative_to(ROOT))
        actual = hashlib.sha256(path.read_bytes()).hexdigest() if path.is_file() and path.stat().st_size > 0 else None
        if actual != expected[name]:
            mismatched.append(name)
    if mismatched:
        raise SystemExit("Missing or checksum-mismatched assets:\n" + "\n".join(mismatched))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check-assets", action="store_true")
    parser.add_argument("--pin-assets", action="store_true")
    parser.add_argument("--migration-path", type=Path, default=product_data_migration())
    parser.add_argument("--manifest-path", type=Path, default=MANIFEST)
    parser.add_argument(
        "--web-evolution-manifest-path",
        type=Path,
        default=WEB_EVOLUTION_MANIFEST,
    )
    parser.add_argument("--battle-json-path", type=Path, default=BATTLE_JSON)
    parser.add_argument("--battle-sha256-path", type=Path, default=BATTLE_SHA256)
    parser.add_argument("--battle-manifest-path", type=Path, default=BATTLE_MANIFEST)
    parser.add_argument("--battle-sql-path", type=Path, default=BATTLE_SQL)
    args = parser.parse_args()
    if args.check_assets and args.pin_assets:
        raise SystemExit("Choose either --check-assets or --pin-assets")
    markdown = PRODUCT.read_text(encoding="utf-8")
    product_data_source, product_extensions = split_product_document(markdown)
    source_checksum = hashlib.sha256(product_data_source.encode()).hexdigest()
    checksum = released_product_checksum()
    chains, templates = catalog.parse(product_data_source)
    battle_payload = battle.parse(product_extensions, chains, templates)
    battle_checksum = battle.checksum(battle_payload)
    args.migration_path.parent.mkdir(parents=True, exist_ok=True)
    args.manifest_path.parent.mkdir(parents=True, exist_ok=True)
    args.web_evolution_manifest_path.parent.mkdir(parents=True, exist_ok=True)
    args.battle_json_path.parent.mkdir(parents=True, exist_ok=True)
    args.battle_sha256_path.parent.mkdir(parents=True, exist_ok=True)
    args.battle_manifest_path.parent.mkdir(parents=True, exist_ok=True)
    args.battle_sql_path.parent.mkdir(parents=True, exist_ok=True)
    args.migration_path.write_text(
        build_sql(chains, templates, checksum, battle_payload), encoding="utf-8"
    )
    previous = json.loads(args.manifest_path.read_text(encoding="utf-8")) if args.manifest_path.is_file() else {}
    assets = previous.get("assets", {}) if previous.get("product_checksum") == checksum else {}
    args.manifest_path.write_text(json.dumps({"version": "v1", "product_checksum": checksum, "chains": chains, "templates": templates, "assets": assets}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.web_evolution_manifest_path.write_text(
        json.dumps(
            build_web_evolution_manifest(templates),
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    args.battle_json_path.write_bytes(battle.json_bytes(battle_payload))
    args.battle_sha256_path.write_text(
        f"{battle_checksum}  battle-v1.json\n", encoding="utf-8"
    )
    args.battle_manifest_path.write_text(
        json.dumps(
            battle.manifest(battle_payload),
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    args.battle_sql_path.write_text(battle.render(battle_payload), encoding="utf-8")
    if args.pin_assets:
        assets = pin_assets(templates)
        args.manifest_path.write_text(json.dumps({"version": "v1", "product_checksum": checksum, "chains": chains, "templates": templates, "assets": assets}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if args.check_assets:
        check_assets(templates, assets)
    print(
        f"product data v1: {len(chains)} chains, {len(templates)} templates, "
        f"release_checksum={checksum}, source_checksum={source_checksum}; "
        f"battle-v1 templates={len(battle_payload['template_configs'])}, "
        f"battle_checksum={battle_checksum}"
    )


if __name__ == "__main__":
    main()
