#!/usr/bin/env python3
"""Build frozen product data SQL and the catalog manifest from the product document."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import catalog
import gacha
import payments
import tasks


ROOT = Path(__file__).resolve().parents[2]
PRODUCT = ROOT / "docs/product/功能说明文档.md"
MIGRATIONS = ROOT / "supabase/migrations"
MANIFEST = ROOT / "generated/catalog/catalog-v1.json"
PLACEHOLDERS = ROOT / "generated/assets/placeholders.json"
ASSET_ROOT = ROOT / "apps/web/public/assets"


def product_data_migration() -> Path:
    matches = sorted(MIGRATIONS.glob("*_product_data_v1.sql"))
    if len(matches) != 1:
        raise RuntimeError(f"Expected one *_product_data_v1.sql migration, found {len(matches)}")
    return matches[0]


def build_sql(chains: list[dict[str, object]], templates: list[dict[str, object]], checksum: str) -> str:
    sections = [
        f"-- Generated by python3 tools/product_data/build.py. Do not hand edit.\n-- Product checksum: {checksum}\n\n",
        catalog.render(chains, templates),
        "\n",
        gacha.render(),
        "\n",
        payments.render(),
        "\n",
        tasks.render(),
    ]
    return "".join(sections)


def asset_files(templates: list[dict[str, object]]) -> list[Path]:
    required = [ROOT / "apps/web/public" / str(item["image_path"]).lstrip("/") for item in templates]
    required += [
        ASSET_ROOT / "boxes/normal.webp",
        ASSET_ROOT / "boxes/rare.webp",
        ASSET_ROOT / "boxes/legendary.webp",
        ASSET_ROOT / "share/preview.webp",
        ASSET_ROOT / "ton/tonconnect-icon.png",
    ]
    return required


def pin_assets(templates: list[dict[str, object]]) -> dict[str, str]:
    required = asset_files(templates)
    missing = [str(path.relative_to(ROOT)) for path in required if not path.is_file() or path.stat().st_size == 0]
    if missing:
        raise SystemExit("Missing required assets:\n" + "\n".join(missing))
    pinned = {str(path.relative_to(ROOT)): hashlib.sha256(path.read_bytes()).hexdigest() for path in required}
    placeholder_manifest = json.loads(PLACEHOLDERS.read_text(encoding="utf-8")) if PLACEHOLDERS.is_file() else {}
    forbidden = set(placeholder_manifest.get("files", {}).values())
    placeholders = sorted(name for name, value in pinned.items() if value in forbidden)
    if placeholders:
        raise SystemExit("Cannot pin development placeholders as production assets:\n" + "\n".join(placeholders))
    return pinned


def check_assets(templates: list[dict[str, object]], expected: object) -> None:
    required = asset_files(templates)
    if not isinstance(expected, dict) or set(expected) != {str(path.relative_to(ROOT)) for path in required}:
        raise SystemExit("Asset checksums are not pinned. Run product data build with --pin-assets after uploading all official assets.")
    mismatched = []
    for path in required:
        name = str(path.relative_to(ROOT))
        actual = hashlib.sha256(path.read_bytes()).hexdigest() if path.is_file() and path.stat().st_size > 0 else None
        if actual != expected[name]:
            mismatched.append(name)
    if mismatched:
        raise SystemExit("Missing or checksum-mismatched assets:\n" + "\n".join(mismatched))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check-assets", action="store_true")
    parser.add_argument("--pin-assets", action="store_true")
    parser.add_argument("--migration-path", type=Path, default=product_data_migration())
    parser.add_argument("--manifest-path", type=Path, default=MANIFEST)
    args = parser.parse_args()
    if args.check_assets and args.pin_assets:
        raise SystemExit("Choose either --check-assets or --pin-assets")
    markdown = PRODUCT.read_text(encoding="utf-8")
    checksum = hashlib.sha256(markdown.encode()).hexdigest()
    chains, templates = catalog.parse(markdown)
    args.migration_path.parent.mkdir(parents=True, exist_ok=True)
    args.manifest_path.parent.mkdir(parents=True, exist_ok=True)
    args.migration_path.write_text(build_sql(chains, templates, checksum), encoding="utf-8")
    previous = json.loads(args.manifest_path.read_text(encoding="utf-8")) if args.manifest_path.is_file() else {}
    assets = previous.get("assets", {}) if previous.get("product_checksum") == checksum else {}
    args.manifest_path.write_text(json.dumps({"version": "v1", "product_checksum": checksum, "chains": chains, "templates": templates, "assets": assets}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if args.pin_assets:
        assets = pin_assets(templates)
        args.manifest_path.write_text(json.dumps({"version": "v1", "product_checksum": checksum, "chains": chains, "templates": templates, "assets": assets}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if args.check_assets:
        check_assets(templates, assets)
    print(f"product data v1: {len(chains)} chains, {len(templates)} templates, {checksum}")


if __name__ == "__main__":
    main()
