export const API_ENDPOINTS = {
  health: "/health",
  auth: {
    telegram: "/auth/telegram",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
  },
  me: {
    bootstrap: "/me/bootstrap",
    assets: "/me/assets",
    profile: "/me/profile",
    notifications: "/me/notifications",
  },
  banners: {
    list: "/banners/list",
  },
  telegram: {
    paymentSupport: "/telegram/payment-support",
  },
  vip: {
    status: "/vip/status",
    createOrder: "/vip/create-order",
    claimDaily: "/vip/claim-daily",
  },
  boxes: {
    list: "/boxes/list",
    rewards: "/boxes/rewards",
    createOpenOrder: "/boxes/create-open-order",
    openVipDaily: "/boxes/open-vip-daily",
    paymentStatus: "/boxes/payment-status",
    result: "/boxes/result",
  },
  inventory: {
    list: "/inventory/list",
    summary: "/inventory/summary",
    groupItems: "/inventory/group-items",
    detail: "/inventory/detail",
    upgrade: "/inventory/upgrade",
    evolve: "/inventory/evolve",
    decompose: "/inventory/decompose",
    sellEntry: "/inventory/sell-entry",
    cancelSell: "/inventory/cancel-sell",
    activity: "/inventory/activity",
  },
  album: {
    progress: "/album/progress",
    series: "/album/series",
    items: "/album/items",
    claimReward: "/album/claim-reward",
    leaderboard: "/album/leaderboard",
  },
  tasks: {
    list: "/tasks/list",
    overview: "/tasks/overview",
    claim: "/tasks/claim",
    checkInStatus: "/tasks/check-in-status",
    checkIn: "/tasks/check-in",
    inviteStats: "/tasks/invite-stats",
    referralLink: "/tasks/referral-link",
    preparedShareMessage: "/tasks/prepared-share-message",
    bindReferral: "/tasks/bind-referral",
    referralRecords: "/tasks/referral-records",
    shareEvent: "/tasks/share-event",
    commissionHistory: "/tasks/commission-history",
    claimCommission: "/tasks/claim-commission",
    rewardHistory: "/tasks/reward-history",
  },
  wallet: {
    challenge: "/wallet/challenge",
    connect: "/wallet/connect",
    proof: "/wallet/proof",
    status: "/wallet/status",
    disconnect: "/wallet/disconnect",
    syncNfts: "/wallet/sync-nfts",
    nfts: "/wallet/nfts",
    transactions: "/wallet/transactions",
    mint: "/wallet/mint",
    mintStatus: "/wallet/mint-status",
  },
  market: {
    listings: "/market/listings",
    listingDetail: "/market/listing-detail",
    buy: "/market/buy",
    sellableItems: "/market/sellable-items",
    sellRules: "/market/sell-rules",
    createListing: "/market/create-listing",
    myListings: "/market/my-listings",
    myListingStats: "/market/my-listing-stats",
    updatePrice: "/market/update-price",
    cancelListing: "/market/cancel-listing",
    stats: "/market/stats",
  },
} as const;

export type ApiEndpointKey = keyof typeof API_ENDPOINTS;
